version: '3'
services:
  nginx:
    build: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        aliases:
          - sf.sfeir.com
    depends_on:
      - scm
      - jenkins
      - sonar
      - nexus
  scm:
    build: ./scm
    image: zbbfufu/scm-manager
    volumes:
      - sources:/home/scm
  jenkins:
    build: ./jenkins
    image: zbbfufu/jenkins
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - scm
      - sonar
      - nexus
  sonar:
    build: ./sonar
    image: zbbfufu/sonar
    volumes:
      - sonar-data:/opt/sonarqube/data
    #environment:
    #- SONARQUBE_JDBC_URL=jdbc:postgresql://pgsql
    #- SONARQUBE_JDBC_USERNAME=
    #- SONARQUBE_JDBC_PASSWORD=
    depends_on:
      - scm
  nexus:
    build: ./nexus
    image: zbbfufu/nexus
    volumes:
      - nexus-repo:/nexus-data

volumes:
  sources:
    driver: local
  jenkins-data:
    driver: local
  sonar-data:
    driver: local
  nexus-repo:
    driver: local
